import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function Home() {
  const [isCookiesEnabled, setIsCookiesEnabled] = useState<boolean>();

  useEffect(() => {
    const { cookieEnabled } = navigator;
    setIsCookiesEnabled(cookieEnabled);
  }, []);

  return (
    <>
      <Head>
        <title>Cookies Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Cookies are {isCookiesEnabled ? 'enabled' : 'disabled'}</h1>
      </main>
    </>
  )
}
